# Generated by Django 5.2.6 on 2025-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='flight',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
