# Generated by Django 5.2.6 on 2025-10-18 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_seat_booking_remove_seat_flight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.booking'),
        ),
        migrations.AddField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10),
        ),
    ]
