# Generated by Django 5.2.6 on 2025-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_seat_booking_seat_flight_alter_seat_seat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
