# Generated by Django 5.2.6 on 2025-10-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_booking_cancelled_at_booking_pnr_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('flight', 'seat_number')},
        ),
    ]
